kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-kafka-connect-operator
subjects:
- kind: ServiceAccount
  name: kubernetes-kafka-connect-operator
roleRef:
  kind: Role
  name: kubernetes-kafka-connect-operator
  apiGroup: rbac.authorization.k8s.io
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: extension-apiserver-authentication-reader-kafkaconnect
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: kubernetes-kafka-connect-operator
  namespace: default
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io